name: bindrnagen
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - ambertools=24.8=cuda_None_nompi_py313hb0f039c_101
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py313h536fd9c_5
  - argtable2=2.13=hd590300_1004
  - arpack=3.9.1=nompi_hf03ea27_102
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - blast=2.17.0=h66d330f_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py313h46c70d0_3
  - bson=0.5.10=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.19.0=h3122c55_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.1.0=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - cffi=1.17.1=py313hfab6e84_0
  - cftime=1.6.4=py313h29aa505_2
  - chardet=5.2.0=pyhd8ed1ab_3
  - clustalo=1.2.4=h503566f_9
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.13.9=py313hd8ed1ab_100
  - cuda-cccl_linux-64=12.9.27=ha770c72_0
  - cuda-crt-dev_linux-64=12.9.86=ha770c72_1
  - cuda-crt-tools=12.9.86=ha770c72_1
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart-static_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-cupti-dev=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_1
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=he02047a_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=h7646684_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.13=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - emboss=6.6.0=h0f19ade_13
  - entrez-direct=24.0=he881be0_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=ha770c72_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - graphite2=1.3.14=h5888daf_0
  - greenlet=3.2.3=py313h46c70d0_0
  - griddataformats=1.0.2=pyhd8ed1ab_1
  - gsd=4.2.0=h31e983c_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.0.0=h76408a6_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h2d575fe_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.0.2=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jax=0.6.0=pyhd8ed1ab_0
  - jaxlib=0.6.0=cuda126py313hb1b46e1_200
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py313h78bf25f_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py313h33d0bda_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.86.0=h6c02f8c_3
  - libboost-python=1.86.0=py313hf0ab243_3
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.4=default_h1df26ce_0
  - libclang13=20.1.4=default_he06ed0a_0
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcublas-dev=12.9.1.4=h9ab20c4_0
  - libcudnn=9.10.1.4=h4840ae0_0
  - libcudnn-dev=9.10.1.4=hcd2ec93_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcufft-dev=11.4.1.4=h5888daf_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcurand-dev=10.3.10.19=h9ab20c4_0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.7.5.82=h9ab20c4_1
  - libcusolver-dev=11.7.5.82=h9ab20c4_1
  - libcusparse=12.5.10.65=h5888daf_1
  - libcusparse-dev=12.5.10.65=h5888daf_1
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgrpc=1.71.0=h8e591d7_1
  - libharu=2.4.5=h943b412_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libllvm20=20.1.4=he9d0ab4_0
  - liblzma=5.6.4=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libnetcdf=4.9.2=nompi_h0134ee8_117
  - libnghttp2=1.64.0=h161d5f1_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=5.29.3=h501fc15_1
  - librdkit=2025.03.4=h84b0b3c_0
  - libre2-11=2025.06.26=hba17884_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.9.2=h65c71a3_0
  - libxml2=2.13.7=h8d12d68_0
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - locarna=1.9.2=h2d50403_1
  - lxml=5.4.0=py313h73548e6_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib-base=3.10.3=py313h129903b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdanalysis=2.10.0=py313h08cd8bf_1
  - mdtraj=1.11.0=py313hf979834_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2022.1.0=hc2b9512_224
  - ml_dtypes=0.5.1=py313ha87cce1_0
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mrcfile=1.5.4=pyhd8ed1ab_0
  - msgpack-python=1.1.2=py313h7037e92_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncbi-vdb=3.2.1=h9948957_0
  - nccl=2.27.5.1=h9b8ff78_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.2=nompi_hee1cade_100
  - netcdf4=1.7.2=nompi_py313ha67fc0a_103
  - nomkl=3.0=0
  - notebook=7.4.4=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.10.2=py313h5f97788_100
  - ocl-icd=2.3.3=hb9d3cd8_0
  - ocl-icd-system=1.0.0=1
  - openblas=0.3.29=pthreads_h6ec200e_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openff-amber-ff-ports=0.0.4=pyhd8ed1ab_1
  - openff-forcefields=2024.09.0=pyhd8ed1ab_1
  - openff-interchange=0.4.2=pyhd8ed1ab_3
  - openff-interchange-base=0.4.2=pyhd8ed1ab_3
  - openff-toolkit=0.16.9=pyhd8ed1ab_0
  - openff-toolkit-base=0.16.9=pyhd8ed1ab_0
  - openff-units=0.3.1=pyhd8ed1ab_1
  - openff-utilities=0.1.15=pyhd8ed1ab_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openmm=8.3.1=py313hc96c04f_0
  - openmmforcefields=0.14.2=pyhd8ed1ab_0
  - openssl=3.5.4=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panedr=0.8.0=pyhd8ed1ab_1
  - parmed=4.3.0=py313hb83d11f_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - pdbfixer=1.11=pyhd8ed1ab_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.213=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.213=pl5321h4dac143_0
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.213=pl5321h503566f_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.0.1=pyh145f28c_0
  - pixman=0.46.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycairo=1.27.0=py313h112314f_0
  - pycparser=2.22=pyh29332c3_1
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pymbar=4.0.3=h78bf25f_3
  - pymbar-core=4.0.3=py313ha014f3b_3
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py313h5f61773_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py313h49b9dc6_6
  - python=3.13.2=hf636f53_101_cp313
  - python-constraint=1.4.0=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-gil=3.13.9=h4df99d1_100
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=5_cp313
  - pytng=0.3.4=py313h75f1e36_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313h8060acc_2
  - pyzmq=26.3.0=py313h8e95178_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - rdkit=2025.03.4=py313hc8d2389_0
  - re2=2025.06.26=h9925aae_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - reportlab=4.4.1=py313h536fd9c_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.26.0=py313h4b2b08d_0
  - scikit-learn=1.7.2=py313h06d4379_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh0d859eb_1
  - six=1.17.0=pyhd8ed1ab_0
  - smirnoff99frosst=1.1.0=pyh44b312d_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlalchemy=2.0.41=py313h536fd9c_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py313h29aa505_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tinydb=4.8.2=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py313h536fd9c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250708=pyhd8ed1ab_0
  - typing_extensions=4.13.0=pyh29332c3_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - validators=0.35.0=pyhd8ed1ab_0
  - viennarna=2.3.5=hfc679d8_2
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wget=1.21.4=hda4d442_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.2.2
      - accelerate==1.5.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - amberutils==21.0
      - biopython==1.85
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - docker-pycreds==0.4.0
      - edgembar==3.0
      - editdistance==0.8.1
      - einops==0.8.1
      - filelock==3.13.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.13.0
      - huggingface-hub==0.30.1
      - jax-cuda12-pjrt==0.6.0
      - jax-cuda12-plugin==0.6.0
      - jinja2==3.1.4
      - keras==3.9.2
      - lightning-utilities==0.14.2
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - memory-efficient-attention-pytorch==0.1.6
      - mmpbsa-py==16.0
      - mpmath==1.3.0
      - multidict==6.2.0
      - namex==0.0.8
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - nvitop==1.4.2
      - optree==0.15.0
      - packmol-memgen==2025.1.29
      - pandas==2.2.3
      - pdb4amber==22.0
      - pillow==11.0.0
      - propcache==0.3.1
      - protobuf==5.29.4
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pymsmt==22.0
      - pytorch-lightning==2.5.1
      - pytraj==2.0.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - sander==22.0
      - scipy==1.15.2
      - sentry-sdk==2.25.0
      - setproctitle==1.3.5
      - setuptools==70.2.0
      - smmap==5.0.2
      - sympy==1.13.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchmetrics==1.7.0
      - torchvision==0.21.0+cu126
      - triton==3.2.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - urllib3==2.3.0
      - wandb==0.19.8
      - yarl==1.18.3
prefix: /data/yzhou/software/miniconda3/envs/bindrnagen
